package com.austin.netty.nettyByProtobuf.domain;

/**
 * @ClassName: MsgBodyOrBuilder
 * @description:
 * @author: zqz
 * @date: 2024/10/22 00:04
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgInfo.proto
public interface MsgBodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.itstack.demo.netty.domain.MsgBody)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string channelId = 1;</code>
     */
    java.lang.String getChannelId();
    /**
     * <code>string channelId = 1;</code>
     */
    com.google.protobuf.ByteString
    getChannelIdBytes();

    /**
     * <code>string msgInfo = 2;</code>
     */
    java.lang.String getMsgInfo();
    /**
     * <code>string msgInfo = 2;</code>
     */
    com.google.protobuf.ByteString
    getMsgInfoBytes();
}
